### ISSUE TITLE
[1] 안드로이드 초기 세팅

### ISSUE THREAD

**Issue by connorcoco** [Gachon-P-project-Epitome/Android#1]
## ✅ To-Do
> 작업 계획 작성
- [ ] 의존성 및 액티비티 기본 세팅
- [ ] activity, fragment 세팅 및 nav설정
- [ ] api 호출 환경 세팅
