### ISSUE TITLE
[Feat] ResultFragment에서 Home으로 돌아가는 액션 구현

### ISSUE THREAD

**Issue by connorcoco** [Gachon-P-project-Epitome/Android#8]
## 📄 작업 내용
- ResultFragment에서 돌아가기 버튼 누를 때 팝업 창으로 데이터가 삭제된다는 고지 구현

## ✅ To-Do
> 작업 계획 작성
- [ ] 돌아가기 버튼클릭 시 데이터 삭제 후 돌아가기
- [ ] 팝업 창 구현(확인->데이터 삭제)
- [ ] 팝업 창 구현(검색결과 없을 때)
